---
- name: Install docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker’s official GPG key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: set up the stable repository
  shell:
    cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: install the latest version of Docker Engine - Community and containerd
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

# docker-compose installation
- name: Download the current stable release of Docker Compose
  shell:
    cmd: curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Apply executable permissions to the binary
  file:
    path: /usr/local/bin/docker-compose
    mode: '755'

- name: Add user to docker group
  user:
    name: "{{ ec2_user }}"
    append: yes
    groups: docker