---
# tasks file for helloworld_flask

#- include_tasks: security-group-id.yml
# - include_tasks: provision.yml
# - include_tasks: ec2-ip.yml
# - include_tasks: inventory_file.yml     # it should be deleted, but {{current_directory}} is used in git_clone.yml
# - include_tasks: timezone.yml
# - include_tasks: docker_installation.yml
#- include_tasks: pyhton_installation.yml
# - include_tasks: security_group.yml
#- include_tasks: git_clone.yml
#- include_tasks: login_ecr.yml
#- include_tasks: certbot_installation.yml
- include_tasks: docker-compose.yml
