---
- name: Provision Ec2
  cloudformation:
    stack_name: "{{ provision_stack_name }}"
    state: present
    region: "{{ provision_region }}"
    disable_rollback: true
    template: cloudformation.template
    template_parameters:
      KeyName: "{{ provision_KeyName }}"
      SecurityGroupIds: "{{ security_group_id.stdout }}"
      InstanceType: "{{ provision_InstanceType }}"
      Image: "{{ provision_Image }}" 
      ServerName: "{{ provision_ServerName }}"
